### ISSUE TITLE
使用您的Occluded-Duke的预训练模型达不到文中的结果

### ISSUE THREAD

**Issue by changshuowang** [WangTaoAs/PFD_Net#10]
作者您好：
感谢你做出如此优秀的工作，我按照reademe的要求在使用您的Occluded-Duke的预训练模型时，发现达不到文中所说的结果，下图是我测试的结果：
![image](https://user-images.githubusercontent.com/49676110/201493498-c12b42a4-fceb-4644-ab17-9385c9486d00.png)
跟论文中的结果大约相差2%，我使用的时pytorch1.7.1, cuda10.2, python3.7.13;所以我想知道这是什么原因造成的呢？
期待您的回复。

**Comment by WangTaoAs** [comment]
The Highest performance is under the Small Sliding Window setting, Step Size is 13.
The released model is under the normal Step Size 16

**Comment by changshuowang** [comment]
> Step Size is 13

Okay, thanks for the author's reply, I looked at the results in your paper again, and the results when running on my machine are equivalent to those in your paper. Thanks again for your excellent work.

**Comment by freeme-create** [comment]
> 作者您好： 感谢你做出如此优秀的工作，我按照reademe的要求在使用您的Occluded-Duke的预训练模型时，发现达不到文中所说的结果，下图是我测试的结果： ![image](https://user-images.githubusercontent.com/49676110/201493498-c12b42a4-fceb-4644-ab17-9385c9486d00.png) 跟论文中的结果大约相差2%，我使用的时pytorch1.7.1， cuda10.2， python3.7.13;所以我想知道这是什么原因造成的呢？ 期待您的回复。



> 时

我的按照原代码设置下map r1 r5 r10分别只能跑到58.7 66.1 79.9 83.7，torch 1.13.1 ，cuda11.3.1，python3.8.19，这些会影响这么大吗
