### ISSUE TITLE
epochs对精度的影响

### ISSUE THREAD

**Issue by Schatzmin** [WangTaoAs/PFD_Net#13]
你好，为了比较PFD_Net和TransReID两个模型在Occlued_Duke上的表现，我把PFD_Net的MAX_EPOCHS改成了和TransReID一样的120，而不是300，得到的结果没有论文中的高，甚至不如TransReID，请问必须把epochs设置成300才能得到更好的结果吗？（300个epochs意味着要在A100上训练1天以上）

**Comment by WangTaoAs** [comment]
Decoder的加入阻碍了模型收敛的速度，同时不准确的Keypoints的引入也可能带来噪声，会导致模型需要更长的收敛时间。
