### ISSUE TITLE
您好作者请问您怎么进行cam可视化的操作的呀？

### ISSUE THREAD

**Issue by ZOUWENMIN** [WangTaoAs/PFD_Net#5]
您好作者请问您怎么进行cam可视化的操作的，没有可视化的代码呀哭。。。

**Comment by zhangz1357117** [comment]
> 您好作者请问您怎么进行cam可视化的操作的，没有可视化的代码呀哭。。。

您好，麻烦问一下，您找到可视化的代码了吗？

**Comment by WangTaoAs** [comment]
> 您好作者请问您怎么进行cam可视化的操作的，没有可视化的代码呀哭。。。

Please Refer to the Grad-CAM in Transformer: https://github.com/jacobgil/pytorch-grad-cam

**Comment by zhangz1357117** [comment]
> > 您好作者请问您怎么进行cam可视化的操作的，没有可视化的代码呀哭。。。
> 
> Please Refer to the Grad-CAM in Transformer: https://github.com/jacobgil/pytorch-grad-cam



> > 您好作者请问您怎么进行cam可视化的操作的，没有可视化的代码呀哭。。。
> 
> Please Refer to the Grad-CAM in Transformer: https://github.com/jacobgil/pytorch-grad-cam

感谢大佬
