### ISSUE TITLE
论文中的sliding window N在代码中对应哪一个参数？

### ISSUE THREAD

**Issue by ChenCherry** [WangTaoAs/PFD_Net#6]
你好 作者 请问 论文中的step size of sliding window的S在代码中对应哪一个参数？没找到┭┮﹏┭┮

**Comment by WangTaoAs** [comment]
在对应的config文件中，修改STRIDE_

**Comment by WangTaoAs** [comment]
在对应的config yml文件中修改STRIDE_SIZE即可
![image](https://user-images.githubusercontent.com/52031839/163696090-29fd1a23-f750-484b-bebb-0cfd020e978a.jpeg)

**Comment by ChenCherry** [comment]
好的 多谢

> 在对应的config yml文件中修改STRIDE_SIZE即可 ![image](https://user-images.githubusercontent.com/52031839/163696090-29fd1a23-f750-484b-bebb-0cfd020e978a.jpeg)

好的 多谢
